version: "3"
services:
  web:
    image: python:latest
    build: .
    container_name: "gawa-python3"
    depends_on:
      - db
    command: python3 app/app.py
    volumes:
      - ./app:/app
    ports:
      - "5002:5002"
    tty: true
  db:
    image: mysql:latest
    container_name: "gawa-mysql"
    ports:
      - "5050:5050"
    env_file:
      - .env