version: "3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "gawa-python3"
    depends_on:
      - db
    volumes:
      - ./app:/app
    ports:
      - "5002:5002"
    command: flask run
    tty: true
  db:
    image: mysql:latest
    container_name: "gawa-mysql"
    ports:
      - "3306:3306"
    env_file:
      - .env